name: Create release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      body:
        required: false
        type: string
        default: ""
      prerelease:
        required: false
        type: boolean
        default: false
      draft:
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.tag }}
          body: ${{ inputs.body }}
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
