name: Semantic release
on:
  push:
    branch:
      - main

permissions:
  contents: read

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 24.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  outputs:
    release_created: ${{ steps.semantic.create_release.outputs.new_release_published }}
    new_tag: $${{ steps.semantic.create_release.outputs.new_release_git_tag }}
    release_notes: ${{ steps.semantic.create_release.outputs.new_release_notes }}
  
  publish-release:
    needs: semantic-release
    if: ${{ needs.semantic-release.outputs.release_created == 'true' }}
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ needs.semantic-release.outputs.new_tag }}
      body: ${{ needs.semantic-release.outputs.new_release_notes }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
